name: Build Rufus

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Rufus
        uses: actions/checkout@v4
        with:
          repository: pbatard/rufus
          ref: refs/tags/v3.15
          path: rufus

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.29

      - name: Build Release
        working-directory: rufus
        # run: msbuild rufus.sln /p:Configuration=Release /p:Platform=x64 /p:DebugSymbols=false /p:EnableEnhancedInstructionSet=AVX2 /p:WholeProgramOptimization=true /p:LinkTimeCodeGeneration=UseLinkTimeCodeGeneration
        run: |
          msbuild rufus.sln /p:Configuration=Release `
          /p:Platform=x64 `
          /p:DebugSymbols=false `
          /p:WholeProgramOptimization=true `
          /p:CL_MP=true `
          /p:RuntimeLibrary=MultiThreadedDLL `
          /p:Optimization=MaxSpeed `
          /p:IntrinsicFunctions=true `
          /p:EnableEnhancedInstructionSet=AVX2 `
          /p:OmitFramePointers=true `
          /p:BasicRuntimeChecks=Default `
          /p:BufferSecurityCheck=false `
          /p:RuntimeTypeInfo=false `
          /p:InlineFunctionExpansion=AnySuitable `
          /p:FavorSizeOrSpeed=Speed `
          /p:FloatingPointModel=Fast `
          /p:LinkTimeCodeGeneration=UseLinkTimeCodeGeneration `
          /p:LinkIncremental=false `
          /p:FloatingPointExceptions=false `
          /p:LinkTimeOptimization=true `
          /p:EnableCOMDATFolding=true `
          /p:OptimizeReferences=true `
          /p:AdditionalLinkOptions="/MERGE:_RDATA=.rdata"

      - name: Archive Binary
        uses: actions/upload-artifact@v4
        with:
          name: rufus
          path: rufus/x64/Release/rufus.exe
